skip_branch_with_pr: true

environment:
  matrix:
    - PYTHON: "C:\\Miniconda37-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library;%PYTHON%\\Library\\bin;%PYTHON%\\Library\\mingw-w64\\bin;%PATH%

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install numpy matplotlib
  - pip install -e .[tests]
  - conda list -e
  - pip freeze

build: false  # Not a C# project

test_script:
  - pytest -v --durations=10
